name: pet_care_app
description: "A Pet Care Application"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ★ 필수 패키지 (버전 최신화)
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.1.1
  image_picker: ^1.1.2

  # 상태 관리 및 UI
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  # 이미지 처리
  cached_network_image: ^3.3.1

  # 유틸리티
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

  # 주소 검색 및 기타
  kpostal: ^1.1.0
  http: ^1.2.1
  file_picker: ^8.0.4
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/products/
    - assets/images/banners/
    - assets/images/community/